# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CuitCuit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CuitCuit
  pod 'Alamofire', '~> 5.0'

  target 'CuitCuitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CuitCuitUITests' do
    # Pods for testing
  end

end
